insert into product_type (name, description, category) values
    ("Apples", "Amazing taste", "Fruit & vegetable"),
    ("Lemons", "Powerful flavour", "Fruit & vegetable"),
    ("Avocados", "Best way to integrate fats in your diet", "Fruit & vegetable"),
    ("Pomegranates", "Packed with a bitter-sweet flavour", "Fruit & vegetable"),
    ("Broccoli", "Perfect for soup", "Fruit & vegetable"),
    ("Leeks", "Best leek in the world", "Fruit & vegetable"),
    ("White onions", "White onion", "Fruit & vegetable"),
    ("Red onions", "Red onion from Tropea", "Fruit & vegetable"),
    ("Green beans", "Unforgettable taste!", "Fruit & vegetable"),
    ("Red beans", "Unforgettable taste n°2!", "Fruit & vegetable"),
    ("Mixed salad", "Fresh and tender", "Fruit & vegetable"),
    ("Fennel", "Rich of fibers!", "Fruit & vegetable"),
    ("Eggplant", "Fried they're the best!", "Fruit & vegetable"),
    ("Garlic", "Pungent taste", "Fruit & vegetable"),
    ("Basil", "Fresh taste for your pizzas!", "Fruit & vegetable"),
    ("Potatoes", "Small potatoes but packed with flavour", "Fruit & vegetable"),
    ("Red potatoes", "Sweet and compact", "Fruit & vegetable"),
    ("Pears", "Sweet and streched", "Fruit & vegetable"),
    ("Kiwis", "Great colour!", "Fruit & vegetable"),
    ("Bananas", "Best bananas directly from Equador", "Fruit & vegetable"),
    ("Peaches", "One of the sweetest fruits", "Fruit & vegetable"),
    ("Carrots", "Few calories and little to no fats!", "Fruit & vegetable"),
    ("Spinach", "Awesome both raw and cooked!", "Fruit & vegetable"),

    ("Clarified butter", "Naturally without lactose", "Dairy"),
    ("Salted butter", "Classic butter, salted", "Dairy"),
    ("Raw milk", "Perfect for breakfasts!", "Dairy"),
    ("Fresh mozzarella", "Every italian must have a mozzarella in his fridge", "Dairy"),
    ("Buffalo mozzarella", "Every neapolitan is happy!", "Dairy"),
    ("Sheep ricotta", "Tender and flavourful", "Dairy"),
    ("Goat ricotta", "Fresh and tasty", "Dairy"),
    ("Stracchino", "Stracchino", "Dairy"),
    ("Greek yogurt 0% fat", "If you go to the gym, you need this! 0% fat!", "Dairy"),
    ("Vanilla yogurt ", "Light yogurt", "Dairy"),

    ("Salami", "Sweet without lactose and gluten", "Meat & cured meat"),
    ("Chicken breast", "Tasty white meat", "Meat & cured meat"),
    ("Rabbit", "Cooked in the oven", "Meat & cured meat"),
    ("Sausages", "Sausages", "Meat & cured meat"),
    ("Hamburger", "Perfect with some iceberg and cheddar", "Meat & cured meat"),
    ("Chicken hamburger", "An alternative if you don't want to eat red meat", "Meat & cured meat"),
    ("Chicken wings", "Delicious! Best with potatoes", "Meat & cured meat"),
    ("Bacon", "Smoked naturally", "Meat & cured meat"),
    ("Bovine meat", "Best red meat!", "Meat & cured meat"),

    ("Homemade taralli", "Handcrafted taralli by nonna Carmen", "Bread & sweets"),
    ("Baguette", "Directly from France", "Bread & sweets"),
    ("Whole grain bread", "Prepared with the best grain!", "Bread & sweets"),
    ("Rustic bread", "Made with a mix of flours", "Bread & sweets"),
    ("5 cereals bread", "With sesami seeds", "Bread & sweets"),
    ("Bread with olives", "If you like olives, this is a no brainer!", "Bread & sweets"),
    ("Biscuits", "Sweet and flavourful", "Bread & sweets"),
    ("Hazelnut cake", "Sweet and soft", "Bread & sweets");